# Generated by Django 4.2.3 on 2023-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_rename_name_emp_الاسم_rename_dep_emp_القطاع_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=50)),
                ('اسم_المورد', models.CharField(max_length=50)),
                ('العنوان', models.CharField(max_length=50)),
                ('رقم_التواصل', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
    ]
